### ISSUE TITLE
event API for validation failure

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-datetime-field#7] opened 2018-01-16 07:12 UTC
We are trying to implement outlook of the validation failure like https://www.predix-ui.com/#/elements/px-validation in React.

![screen shot 2018-01-16 at 3 59 11 pm](https://user-images.githubusercontent.com/1262296/34977626-3e358330-fad6-11e7-94f2-6ee782f7ddd3.png)

However, for predix date components, current validation failure appearance is as below.
![image](https://user-images.githubusercontent.com/1262296/34975781-63518112-face-11e7-89e0-b7964619dd95.png)
Is that ok to provide some event API when validation failed, e.g., onValidationFailed, so that we are able to customize our own validation behavior, e.g,
* Be able to turn field label (**Submitted date**) to red when validation failed.
* Customize our own validation message, e.g., change validation message from uppercase to lowercase.

**Comment by randyaskin** [comment] 2018-01-16 19:02
The datetime components all fire `px-moment-valid` and `px-moment-invalid` as a result of the validation logic in px-datetime-common, which you can use for your first bullet point. The second bullet point would require us to expose a CSS variable in this repo, as we currently don't allow any way for you to set the case of the validation message (it's being transformed with `text-transform:uppercase`).

**Comment by dargonwanglong** [comment] 2018-01-19 11:46
@randyaskin 

I tried px-moment-invalid with the px-datetime-picker component, but my custom function was not triggered. Would you please help check?

**Code Example**
https://codesandbox.io/s/v1y2810v00

**Other issues**
We are using moment-obj-changed to get the new value, but it does not work in these cases:
1. No validation error even if the input is incomplete?
After clearing the year or hour value, there are no errors or warnings to remind me that the input is incomplete. It looks like the input is valid. But it will not trigger moment-obj-changed.

Cleared year and hour:
<img width="359" alt="input_incomplete" src="https://user-images.githubusercontent.com/16732869/35148792-98a749d2-fd4e-11e7-8cf9-97c0746292bf.png">

2. How do I clear the value after setting a value for the component?
In some cases, user may want to clear the current value and leave it as empty. But the moment-obj-changed is not triggered after all inputs have been cleared. It looks like the value cannot be cleared after initialized.

**Comment by randyaskin** [comment] 2018-01-19 15:33
@katemenkhaus let's take a look at this if you have some time later. The "incomplete" validation and clearing of the momentObj don't seem to be working like they were a few weeks ago (unless I'm missing something).

**Comment by katemenkhaus** [comment] 2018-01-19 17:38
The component is working as expected. Nothing has changed in the last few weeks. 
Some of the components run validation on blur but not all of them. This is an inconstancy in our code but it was also never a requirement. 
@dargonwanglong If you were to hit `enter` in any of those cases you would see the validation error you expect. We don't want to show invalid while a user is in the process of changing the field. We only want to should validation when the user is "done" interacting with the field. When there are no buttons the only way we know if the user is "done" interacting with the field is if they hit `enter` or move away from the field. 
I am in the process of added validation on blur. Will have an update soon.

**Comment by katemenkhaus** [comment] 2018-01-19 17:44
@dargonwanglong can you please confirm if you are having an issue with `px-datetime-picker` which is the codesandbox you sent more or `px-datetime-field`

**Comment by katemenkhaus** [comment] 2018-01-22 18:24
Pushed a fix to `px-datetime-field v2.0.7` that will validate the field when the user is not longer focused on it.

**Closed as completed by katemenkhaus** 2018-01-22 18:24 UTC

**Comment by dargonwanglong** [comment] 2018-01-23 01:14
Confirmed, works for me now. Thanks!
